name: Doxygen Docs

on:
  push:
    branches:
      - docs

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # don't clone submodules, because submodules is private repository

      - name: Clone doxygen-awesome-css
        run: |
          git clone https://github.com/jothepro/doxygen-awesome-css.git
          #- name: Clone Private Repository with using PAT
          #  env:
          #    PAT: ${{ secrets.GH_PAT }} # PAT subcribed in Secrets
          #  run: |
          #    git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/kamitsui/cpp00.git
          #    git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/kamitsui/cpp_getting_start.git
          #    git clone https://github.com/jothepro/doxygen-awesome-css.git
      
          #- name: Use Cloned Repo
          #  run: |
          #    ls
          #    cd cpp00
          #    ls -la


      - name: Install Doxygen
        run: |
          sudo apt update
          sudo apt-get install -y doxygen graphviz rsync

      - name: Generate Documentation
        run: |
          doxygen --version
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        if: github.actor != 'nektos/act' # Skip deployment locally
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: html
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
