name: Doxygen Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # don't clone submodules here
            #submodules: true  # Ensure submodules are checked out

            #- name: Configure Git Credentials
            #  env:
            #    PAT: ${{ secrets.GH_PAT }} # PAT subcribed in Secrets
            #  run: |
            #    git config --global user.email "kamitsui@student.42tokyo.jp" # 適切なメールアドレスに置き換える
            #    git config --global user.name "kamitsui"           # 適切な名前に置き換える
            #    git config --global credential.helper store
            #    echo "https://github.com" >> $GITHUB_WORKSPACE/.git-credentials
            #    echo "username=$GITHUB_ACTOR" >> $GITHUB_WORKSPACE/.git-credentials
            #    echo "password=$PAT" >> $GITHUB_WORKSPACE/.git-credentials
            #    chmod 0400 $GITHUB_WORKSPACE/.git-credentials

      - name: Clone Private Repository with using PAT
        env:
          PAT: ${{ secrets.GH_PAT }} # PAT subcribed in Secrets
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/kamitsui/cpp00.git
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/kamitsui/cpp_getting_start.git
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/kamitsui/doxygen-awesome-css.git
      
      - name: Use Cloned Repo
        run: |
          ls
          cd cpp00
          ls -la


      - name: Install Doxygen
        run: |
          sudo apt update
          sudo apt-get install -y doxygen graphviz rsync

          #- name: Configure Doxygen with Doxygen Awesome CSS
          #  run: |
          # Ensure the CSS theme is properly linked
          #cp docs/doxygen-awesome-css/doxygen-awesome.css .
          #cp docs/doxygen-awesome-css/doxygen-awesome-sidebar-only.css .
          #cp docs/doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js .

          # Modify the Doxyfile to use the theme
          #sed -i 's|HTML_EXTRA_STYLESHEET.*|HTML_EXTRA_STYLESHEET = doxygen-awesome.css doxygen-awesome-sidebar-only.css|' Doxyfile
          #sed -i 's|HTML_EXTRA_FILES.*|HTML_EXTRA_FILES = doxygen-awesome-darkmode-toggle.js|' Doxyfile
          #
          ## Ensure OUTPUT_DIRECTORY is set to 'html' for deployment consistency
          #sed -i 's|^OUTPUT_DIRECTORY.*|OUTPUT_DIRECTORY = ./|' Doxyfile

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        if: github.actor != 'nektos/act' # Skip deployment locally
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: html
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
